### ISSUE TITLE
could not run "pip install pandas_talib"

### ISSUE THREAD

**Issue by fdavidg** [femtotrader/pandas_talib#17]
When I tried to install pandas_tali using the command "pip install pandas_talib" I get the following error:

"  Could not find a version that satisfies the requirement pandas_talib (from versions: )
No matching distribution found for pandas_talib"

Could anyone help?

**Comment by femtotrader** [comment]
No pip version
see https://github.com/femtotrader/pandas_talib#development to install latest development version
