### ISSUE TITLE
add code health to the project

### ISSUE THREAD

**Issue by llazzaro** [femtotrader/pandas_talib#9]
Hi,

I was reviewing the code. I found some pep8 violations in the code (which I'm fixing).

I recommend to add this https://landscape.io

Also I recommend to view this video https://www.youtube.com/watch?v=wf-BqAjZb8M

**Comment by llazzaro** [comment]
this was already added

**Comment by femtotrader** [comment]
Thanks.
I also need to learn some tools such a tox.
